#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor DP-4 -d 6 7 8 9 0

bspc config border_width        3
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#b79fe3"
bspc config active_border_color "#484848"
bspc config normal_border_color "#484848"

# Auto Set Monitors
xrandr --output DP-2 --primary --mode 1920x1080 --rotate normal --rate 120 --output DP-4 --mode 2560x1440 --rotate normal --rate 60 --right-of DP-2

# Auto set cursor
xsetroot -cursor_name left_ptr

# Auto Start
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
~/.config/dunst/launchdunst.sh &
~/.config/polybar/launch.sh &
~/.config/polybar/scripts/nm.sh &
~/.config/polybar/scripts/clipboard.sh &
clipit &
